// Vue/eleme/src/App.vue
<template>
  <div>
    <v-header :seller="seller" />
  </div>
</template>
<script>
import { getSellerRequest } from './api/request'
import header from './components/header/header.vue'

export default {
  data() {
    return {
      seller: {}
    }

  },
  mounted() {
    const getSellerData = async () => {
      const { data } = await getSellerRequest()
      this.seller = data
      // console.log(this.seller);
    }
    getSellerData()
  },
  components: {
    'v-header': header
  }
}
</script>
<style scoped>
</style>

// react/bilibili-react-ts-fullstack/src/App.tsx
import { useState, useEffect } from 'react'
import './App.css'
import { getVideosRequest } from '@/api/index'

function App() {
  useEffect(() => {
    getVideosRequest()
      .then(data => {
        console.log(data, '/////////')
      })
  }, [])
  return (
    <div className="App">

    </div>
  )
}

export default App
